services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    command: uv run uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  # For Phase 2: Add Redis for job persistence
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped

# volumes:
#   redis-data: 