[project]
name = "async-fetcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "patchright>=1.52.5",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "ruff>=0.12.4",
    "structlog>=25.4.0",
    "uvicorn[standard]>=0.35.0",
]
